### ISSUE TITLE
Hierarchical Clustering not working in new version of phantasus

### ISSUE THREAD

**Issue by shashj** [ctlab/phantasus#109] opened 2019-02-04 17:12 UTC
I am a big fan of phantasus, for the previous 2 days, Hierarchical Clustering is throwing an error. I am getting this error in the console.

```
1.3.3 - master-537
phantasus-external-other.min.js:1 Setting path to local (non-CORS) server https://genome.ifmo.ru/ocpu/library/phantasus/R
(index):38 Uncaught TypeError: Cannot read property 'message' of null
    at window.onerror ((index):38)

```

**Comment by vlakam** [comment] 2019-02-04 17:36
Hello.

First of all sorry for the inconvenience caused by this issue. Fix is already merged into master and currently we are working on deploying new build. 

Stay tuned.

**Comment by shashj** [comment] 2019-02-04 17:37
Thanks for the response @vlakam , waiting eagerly for the deployment

**Comment by assaron** [comment] 2019-02-04 18:56
The fixed version should be available now on both genome.ifmo.ru/phantasus and artyomovlab.wustl.edu/phantasus mirrors. You probably have to refresh it with Ctrl-F5 first, so it shows in console "1.3.4 - master-548" message

**Closed by assaron** 2019-02-04 18:56 UTC

**Comment by shashj** [comment] 2019-02-05 04:14
Thank you so much @assaron, it works now
