### ISSUE TITLE
Sweep runs but gives non-numeric error

### ISSUE THREAD

**Issue by saksham219** [ctlab/phantasus#150] opened 2020-01-02 11:16 UTC
![image](https://user-images.githubusercontent.com/28567402/71664536-4d590e80-2d7f-11ea-87c4-dd4d20a34212.png)

Probably this is because the target in sweep call is being read as character vector

**Comment by assaron** [comment] 2021-11-02 09:23
I can't reproduce the error, but hope it is fixed now, as we've update annotation type handling (currently deployed only on https://ctlab.itmo.ru/phantasus-dev/)

**Closed by assaron** 2021-11-02 09:23 UTC
